# Generated by Django 5.1.1 on 2024-09-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrition',
            new_name='description',
        ),
    ]
