# Generated by Django 5.1.1 on 2024-09-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_descrition_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
